#!/usr/bin/env python3
"""
hops_site_run.py — run HOPS for one site with technical-assumption overrides, without editing hops_core.py.

    # validate: reproduce a published v7 point and diff it against the Sherlock CSV
    python3 hops_site_run.py --validate 61 --ccs No --ci 0.5 --results ~/Documents/Stanford/PhD/HOPS/results/sherlock_v7

    # a run request from the atlas "Build a plant" page
    python3 hops_site_run.py --spec request.json --out ./site_runs

How the override hook works
---------------------------
hops_core.py is read, three multiplier hooks are inserted at exact anchor lines (SMR CAPEX, CCS CAPEX,
CCS capture rates — the only technical settings that are hardcoded inside build_model), and the result is
written as a *generated* module `_generated/hops_core_site.py` next to this script. hops_core.py itself is
never modified; if an anchor no longer matches, this script stops and says which one. With every override
at its default the generated module is numerically identical to the original — `--validate` proves that.

Everything else is switched the way the Sherlock array switches it: environment variables that hops_core
already reads (HOPS_C_EL, HOPS_PV_CAPEX_MULT, HOPS_WT_CAPEX_MULT, HOPS_C_B_AVG, HOPS_NG_PRICE_MULT,
HOPS_GRID_PRICE_MULT, HOPS_RES_OVERBUILD, HOPS_EL_MINLOAD, HOPS_NH3_MINLOAD, HOPS_ASU_MINLOAD, HOPS_HB_HOURS,
HOPS_INTEREST_RATE, HOPS_CCS, HOPS_PATHWAY, HOPS_OBJECTIVE) plus module attributes set after import for the
few module-level constants (NH3 price, EUA price, ETS switch).

Output layout = the Sherlock layout, so tools/hops_to_web.py ingests it unchanged:
    <out>/CI_Range_{PATHWAY}_plant{ID}_CCS{Yes|No}_{LABEL}.csv
    <out>/hourly/hourly_{PATHWAY}_plant{ID}_CCS{Yes|No}_CI{ci:.2f}_{LABEL}.parquet
    <out>/sites.json                         custom-site register (id, name, lat, lon, tNH3_day, spec)
Custom sites get ids from 1000 upwards so they never collide with the 0–94 plant list.
"""
from __future__ import annotations
import argparse, importlib.util, json, os, sys, time
from pathlib import Path

HERE = Path(__file__).resolve().parent
HOPS_CODE = Path(os.environ.get("HOPS_CODE_DIR", Path.home() / "Documents/Stanford/PhD/HOPS/Sherlock all Plants/New"))
HOPS_DATA = Path(os.environ.get("HOPS_DATA_DIR", Path.home() / "Documents/Stanford/PhD/HOPS/HOPS_DATA"))
GEN = HERE / "_generated"

# ----------------------------------------------------------------- 1. the hook: three anchors, three multipliers
HOOKS = [
    # SMR (reformer) CAPEX — hardcoded $/tpd H2 by region
    ('        C_SMR = (2037453 if _IS_US_REGION else 1836845) * 1.4 * SCALE  # $/tpd H2: US | EU (MAKSIM). REVIEW.',
     '        C_SMR = (2037453 if _IS_US_REGION else 1836845) * 1.4 * SCALE * _envf("HOPS_C_SMR_MULT", 1.0)  # $/tpd H2: US | EU (MAKSIM). REVIEW.  [site-run hook]'),
    # CCS CAPEX — process-stream unit cost and the flue-gas (PCCU) quote
    ('            capex_ccs_process = 150.0  # $/(tCO2/yr)',
     '            capex_ccs_process = 150.0 * _envf("HOPS_C_CCS_MULT", 1.0)  # $/(tCO2/yr)  [site-run hook]'),
    ('            PCCU_QUOTE_USD  = 143.0e6',
     '            PCCU_QUOTE_USD  = 143.0e6 * _envf("HOPS_C_CCS_MULT", 1.0)  # [site-run hook]'),
    # CCS capture rates — per-pathway table; override applies to whichever pathway is active
    ('    _ccs = CCS_PARAMS[PATHWAY]\n',
     '    _ccs = dict(CCS_PARAMS[PATHWAY])\n'
     '    if os.environ.get("HOPS_CCS_CAP_PROC"): _ccs["cap_proc"] = float(os.environ["HOPS_CCS_CAP_PROC"])  # [site-run hook]\n'
     '    if os.environ.get("HOPS_CCS_CAP_HEAT"): _ccs["cap_heat"] = float(os.environ["HOPS_CCS_CAP_HEAT"])  # [site-run hook]\n'),
]

def generate_module() -> Path:
    src = (HOPS_CODE / "hops_core.py").read_text(encoding="utf-8")
    for old, new in HOOKS:
        c = src.count(old)
        if c != 1:
            sys.exit(f"[hook] anchor found {c}x (need exactly 1) in hops_core.py — the model changed, update HOOKS:\n  {old.strip()[:100]}")
        src = src.replace(old, new)
    GEN.mkdir(exist_ok=True)
    out = GEN / "hops_core_site.py"
    header = ("# GENERATED by hops_site_run.py from hops_core.py — DO NOT EDIT. Regenerated on every run.\n"
              f"# Source: {HOPS_CODE / 'hops_core.py'}\n")
    out.write_text(header + src, encoding="utf-8")
    return out

# ----------------------------------------------------------------- 2. overrides: spec keys → what hops_core reads
# value: (env var, transform)  or  ("attr", module attribute name)
OVERRIDES = {
    "el_capex_usd_per_kw":     ("HOPS_C_EL",           lambda v: v * 1000.0),   # $/kW → $/MW
    "pv_capex_mult":           ("HOPS_PV_CAPEX_MULT",  float),
    "wt_capex_mult":           ("HOPS_WT_CAPEX_MULT",  float),
    "battery_capex_usd_per_mwh": ("HOPS_C_B_AVG",      float),
    "smr_capex_mult":          ("HOPS_C_SMR_MULT",     float),                 # hook
    "ccs_capex_mult":          ("HOPS_C_CCS_MULT",     float),                 # hook
    "ccs_capture_process":     ("HOPS_CCS_CAP_PROC",   float),                 # hook, 0–1
    "ccs_capture_flue":        ("HOPS_CCS_CAP_HEAT",   float),                 # hook, 0–1
    "hb_capex_usd_per_mwh":    ("HOPS_C_HB",           float),
    "compressor_capex_usd_per_mw": ("HOPS_C_CP",       float),
    "gas_price_mult":          ("HOPS_NG_PRICE_MULT",  float),
    "grid_price_mult":         ("HOPS_GRID_PRICE_MULT", float),
    "res_overbuild":           ("HOPS_RES_OVERBUILD",  float),
    "el_minload":              ("HOPS_EL_MINLOAD",     float),
    "nh3_minload":             ("HOPS_NH3_MINLOAD",    float),
    "asu_minload":             ("HOPS_ASU_MINLOAD",    float),
    "hb_hours":                ("HOPS_HB_HOURS",       float),
    "export_frac":             ("HOPS_EXPORT_FRAC",    float),
    "interest_rate":           ("HOPS_INTEREST_RATE",  float),
    "p_el_ub_mw":              ("HOPS_P_EL_UB",        float),
    "p_b_ub_mwh":              ("HOPS_P_B_UB",         float),
    "p_st_ub_t":               ("HOPS_P_ST_UB",        float),
    # module-level constants (set after import)
    "nh3_price_usd_per_t":     ("attr", ["NH3_PRICE_EUROPE", "NH3_PRICE_US"]),
    "eua_price_eur_per_t":     ("attr", ["EUA_PRICE_EUR"]),
    "eu_ets":                  ("attr", ["EU_ETS"]),                          # "Yes"/"No"
}

def apply_env(spec: dict, bau: bool = False) -> dict:
    """Set the run-level environment. Returns the attribute overrides to apply after import."""
    os.environ.setdefault("HOPS_DATA_DIR", str(HOPS_DATA))
    os.environ.setdefault("GRB_LICENSE_FILE", str(Path.home() / "gurobi.lic"))
    os.environ["HOPS_RUN_MODE"] = "BAU" if bau else "CI"
    os.environ["HOPS_PATHWAY"] = spec.get("pathway_code", "SMR_INT_ASU")
    os.environ["HOPS_OBJECTIVE"] = "LCOA" if bau else spec.get("objective", "IRR")   # BAU must be solved on LCOA (README_SHERLOCK)
    os.environ["HOPS_CCS"] = "Yes" if spec.get("ccs") else "No"
    attrs = {}
    for k, v in (spec.get("overrides") or {}).items():
        if k not in OVERRIDES: print(f"[override] unknown key ignored: {k}"); continue
        target, tf = OVERRIDES[k]
        if target == "attr":
            for a in tf: attrs[a] = v
        else:
            os.environ[target] = str(tf(v)); print(f"[override] {target}={os.environ[target]}")
    return attrs

def import_site_core(attrs: dict):
    sys.path.insert(0, str(HOPS_CODE))
    cwd = os.getcwd(); os.chdir(HOPS_CODE)                 # hops_core creates ./results relative to cwd
    path = generate_module()
    spec = importlib.util.spec_from_file_location("hops_core_site", path)
    hc = importlib.util.module_from_spec(spec); spec.loader.exec_module(hc)
    os.chdir(cwd)
    for a, v in attrs.items():
        if not hasattr(hc, a): sys.exit(f"[override] hops_core has no attribute {a}")
        setattr(hc, a, v); print(f"[override] hops_core.{a}={v!r}")
    return hc

# ----------------------------------------------------------------- 3. run one site
NO_RETURN = "no positive return"      # hops_finance_objective: AnnualCF <= 0 — the design cannot earn any return at the NH3 price

def run_site(spec: dict, out: Path, label: str, site_id: int, ci_targets, fallback_lcoa: bool = False):
    """Solve the CI targets. A target whose IRR solve has no positive return is SKIPPED and recorded (sites.json →
    skipped[CCS][ci]) — the same convention as the fleet runs, where such points are simply absent — unless
    fallback_lcoa is set, in which case it is re-solved on the LCOA (cost-minimising) objective and tagged so."""
    import numpy as np, pandas as pd
    from shapely.geometry import Point
    attrs = apply_env(spec)
    hc = import_site_core(attrs)
    from weather_loading_2025_atlite import load_cf_timeseries
    lat, lon, tpd = float(spec["lat"]), float(spec["lon"]), float(spec["tNH3_day"])
    region = hc.get_region(Point(lon, lat), hc.countries, hc.us_states, sovereignt_override=spec.get("country"))
    print(f"site {site_id} '{spec.get('name','')}' {lat:.4f},{lon:.4f}  {tpd:.1f} t/d  region={region}  CCS={os.environ['HOPS_CCS']}  pathway={os.environ['HOPS_PATHWAY']}")
    solar, wind = load_cf_timeseries(lat, lon, T=8760, region=region)
    if np.any(np.isnan(solar)) or np.any(np.isnan(wind)): sys.exit("NaN in capacity-factor series for this site")
    out.mkdir(parents=True, exist_ok=True); (out / "hourly").mkdir(exist_ok=True)
    P, C = os.environ["HOPS_PATHWAY"], os.environ["HOPS_CCS"]
    tags = dict(plant_idx=site_id, lat=lat, lon=lon, country=spec.get("country", ""), RUN_MODE="CI", PATHWAY=P,
                OBJECTIVE=os.environ["HOPS_OBJECTIVE"], CCS=C, LABEL=label, site_name=spec.get("name", ""))
    rows = []; skipped = {}; errors = {}
    for ci in ci_targets:
        t0 = time.time(); print(f"\n--- CI {ci} ---"); fell_back = False
        try:
            try:
                dd, dfop = hc.run_optimization_for_point(lat, lon, solar, wind, tpd, NH3_intensity_target=ci, ci_series_override=None)
            except ValueError as e:
                if NO_RETURN not in str(e): raise
                if not fallback_lcoa:
                    skipped[f"{ci:.2f}"] = f"no design earns a positive return at the NH3 price ({getattr(hc, 'NH3_PRICE_US' if region == 'US' else 'NH3_PRICE_EUROPE', 'model')} $/t) — skipped, as in the fleet runs"
                    print(f"[SKIP] CI={ci}: {skipped[f'{ci:.2f}']}"); continue
                print(f"[FALLBACK] CI={ci}: no positive return on the IRR objective → re-solving on LCOA (cost minimum)")
                os.environ["HOPS_OBJECTIVE"] = "LCOA"; hc = import_site_core(attrs); fell_back = True
                try: dd, dfop = hc.run_optimization_for_point(lat, lon, solar, wind, tpd, NH3_intensity_target=ci, ci_series_override=None)
                finally: os.environ["HOPS_OBJECTIVE"] = spec.get("objective", "IRR"); hc = import_site_core(attrs)
        except Exception as e:
            import traceback; print(f"[WARN] CI={ci} failed: {type(e).__name__}: {e}"); traceback.print_exc(); errors[f"{ci:.2f}"] = f"{type(e).__name__}: {e}"[:300]; continue
        if dd is None: print(f"[WARN] CI={ci} no optimal solution"); errors[f"{ci:.2f}"] = "no optimal solution"; continue
        dd.update(tags); dd["CI_target"] = ci; dd["overrides"] = json.dumps(spec.get("overrides") or {})
        if fell_back: dd["OBJECTIVE"] = "LCOA (fallback: no positive return on IRR)"
        rows.append(dd)
        if dfop is not None and not dfop.empty:
            df = dfop.copy(); df.attrs = {}
            for k, v in tags.items(): df[k] = v
            df["CI_target"] = ci
            df.to_parquet(out / "hourly" / f"hourly_{P}_plant{site_id}_CCS{C}_CI{ci:.2f}_{label}.parquet", index=False)
        pd.DataFrame(rows).to_csv(out / f"CI_Range_{P}_plant{site_id}_CCS{C}_{label}.csv", index=False)
        print(f"done {time.time()-t0:.0f}s  z_cost={dd.get('z_cost $/ton NH3'):.1f} $/t   [{len(rows)}/{len(ci_targets)}]")
    reg = out / "sites.json"; sites = json.loads(reg.read_text()) if reg.exists() else {}
    ent = sites.get(str(site_id)) or {}
    ent.update({"id": site_id, "name": spec.get("name", ""), "lat": lat, "lon": lon, "tNH3_day": tpd, "country": spec.get("country", ""),
                "region": region, "spec": spec, "label": label, "n_ci": ent.get("n_ci", 0) + len(rows)})
    ent.setdefault("skipped", {}).setdefault(C, {}).update(skipped); ent.setdefault("errors", {}).setdefault(C, {}).update(errors)   # per CCS state, merged across jobs by the publish step
    sites[str(site_id)] = ent; reg.write_text(json.dumps(sites, indent=1))
    if errors and not rows: sys.exit(f"[FAIL] site {site_id} CCS={C}: {errors}")   # a real failure goes red; skipped-for-no-return points do not
    if skipped and not rows: print(f"[DONE] site {site_id} CCS={C}: every requested CI target skipped — {skipped}")
    return rows

def run_bau(spec: dict, out: Path, bau_label: str, site_id: int):
    """The BAU reference for a custom site: one unconstrained cost-minimising solve, CCS off (CCS is irrelevant to it)."""
    import numpy as np, pandas as pd
    from shapely.geometry import Point
    spec = {**spec, "ccs": False}
    attrs = apply_env(spec, bau=True); hc = import_site_core(attrs)
    from weather_loading_2025_atlite import load_cf_timeseries
    lat, lon, tpd = float(spec["lat"]), float(spec["lon"]), float(spec["tNH3_day"])
    region = hc.get_region(Point(lon, lat), hc.countries, hc.us_states, sovereignt_override=spec.get("country"))
    solar, wind = load_cf_timeseries(lat, lon, T=8760, region=region)
    out.mkdir(parents=True, exist_ok=True); (out / "hourly").mkdir(exist_ok=True); P = os.environ["HOPS_PATHWAY"]
    t0 = time.time(); dd, dfop = hc.run_optimization_for_point(lat, lon, solar, wind, tpd, NH3_intensity_target=None, ci_series_override=None)
    if dd is None: sys.exit("BAU returned no optimal solution")
    tags = dict(plant_idx=site_id, lat=lat, lon=lon, country=spec.get("country", ""), RUN_MODE="BAU", PATHWAY=P, OBJECTIVE="LCOA", CCS="No", LABEL=bau_label, site_name=spec.get("name", ""))
    dd.update(tags)
    fp = out / f"BAU_AllPlants_{P}_CCSNo_{bau_label}.csv"
    old = pd.read_csv(fp) if fp.exists() else pd.DataFrame()
    if len(old) and "plant_idx" in old: old = old[old["plant_idx"] != site_id]
    pd.concat([old, pd.DataFrame([dd])], ignore_index=True).to_csv(fp, index=False)
    if dfop is not None and not dfop.empty:
        df = dfop.copy(); df.attrs = {}
        for k, v in tags.items(): df[k] = v
        df.to_parquet(out / "hourly" / f"hourly_BAU_{P}_plant{site_id}_CCSNo_{bau_label}.parquet", index=False)
    print(f"BAU done {time.time()-t0:.0f}s  z_cost={dd.get('z_cost $/ton NH3'):.1f} $/t → {fp.name}")

# ----------------------------------------------------------------- 4. validation against a published Sherlock point
COMPARE = ["z_cost $/ton NH3", "LCOA_ammonia_only_LCOE", "LCOA_ammonia_only_EXPORT", "P_PV MW", "P_WT MW", "P_EL MW", "P_B MW",
           "P_SMR tons H2/day", "P_HB MW", "Carbon Intensity tCO2/tNH3 with CCS", "Project IRR %", "CAPEX overnight $"]

def validate(plant_idx: int, ccs: str, ci: float, results: Path, label: str):
    import pandas as pd
    ref = pd.read_csv(results / f"CI_Range_SMR_INT_ASU_plant{plant_idx}_CCS{ccs}_{label}.csv")
    row = ref[(ref["Target_NH3_CO2_intensity_kgCO2_per_kgNH3"] - ci).abs() < 1e-6].iloc[0]
    spec = {"name": f"validate plant{plant_idx}", "lat": float(row["lat"]), "lon": float(row["lon"]), "tNH3_day": float(row["tNH3_day"]),
            "country": str(row["country"]), "ccs": ccs == "Yes", "pathway_code": "SMR_INT_ASU", "objective": "IRR", "overrides": {}}
    out = HERE / "_validation"
    rows = run_site(spec, out, "validate", plant_idx, [ci])
    if not rows: sys.exit("validation run produced no row")
    got = rows[0]
    print("\n=== validation: local (this Mac, generated module, no overrides) vs Sherlock " + label + " ===")
    print(f"{'column':42s} {'sherlock':>16s} {'local':>16s} {'rel diff':>10s}")
    worst = 0.0
    for c in COMPARE:
        a, b = float(row[c]), float(got.get(c, float("nan")))
        rel = abs(a - b) / max(abs(a), 1e-9); worst = max(worst, rel if abs(a) > 1e-6 else 0)
        print(f"{c:42s} {a:16.4f} {b:16.4f} {rel:10.2e}")
    print(f"\nworst relative difference: {worst:.2e}  → {'IDENTICAL within solver tolerance' if worst < 1e-3 else 'DIFFERS — investigate before trusting the hook'}")

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", help="run-request JSON from the atlas (site, plant, overrides)")
    ap.add_argument("--out", default="site_runs"); ap.add_argument("--label", default="site_v1")
    ap.add_argument("--site-id", type=int, help="custom site id (default: next free from 1000)")
    ap.add_argument("--ci", default=None, help="comma list of CI targets (default 0..1.75)")
    ap.add_argument("--validate", type=int, metavar="PLANT", help="reproduce a v7 point for this plant and diff it")
    ap.add_argument("--ccs", default="No"); ap.add_argument("--results", default=str(Path.home() / "Documents/Stanford/PhD/HOPS/results/sherlock_v7"))
    ap.add_argument("--ref-label", default="IRR_v7")
    ap.add_argument("--only-ccs", choices=["Yes", "No"], help="solve only this CCS state (cloud matrix jobs)")
    ap.add_argument("--bau", action="store_true", help="solve the BAU reference for the spec's site instead of the CI sweep")
    ap.add_argument("--bau-label", default=None, help="label for the BAU file (default: same as --label)")
    ap.add_argument("--fallback-lcoa", action="store_true", help="re-solve a CI point on the LCOA objective when the IRR objective finds no positive return (default: skip it like the fleet runs)")
    a = ap.parse_args()
    if a.validate is not None:
        validate(a.validate, a.ccs, float(a.ci or 0.5), Path(a.results), a.ref_label); return
    if not a.spec: ap.error("--spec or --validate required")
    spec = json.loads(Path(a.spec).read_text())
    runs = []
    if "site" in spec:   # the atlas request format: both pathways, full CI sweep, technical inputs resolved
        T = spec.get("technical", {}) or {}
        paths = spec["plant"].get("pathways") or [spec["plant"].get("pathway", "SMR")]
        cis_spec = spec["plant"].get("ci_targets") if isinstance(spec["plant"].get("ci_targets"), list) else None
        for pth in paths:
            runs.append(({"name": spec["site"].get("name"), "lat": spec["site"]["lat"], "lon": spec["site"]["lon"], "tNH3_day": spec["plant"]["tNH3_day"],
                          "ccs": "+CCS" in pth, "pathway_code": "SMR_INT_ASU", "objective": "IRR", "overrides": T, "country": spec["site"].get("country")}, cis_spec))
    else:
        runs.append((spec, None))
    out = Path(a.out); reg = out / "sites.json"; sites = json.loads(reg.read_text()) if reg.exists() else {}
    site_id = a.site_id or (max([int(k) for k in sites] + [999]) + 1)
    if a.bau:
        run_bau(runs[0][0], out, a.bau_label or a.label, site_id); return
    for sp, cis_spec in runs:
        if a.only_ccs and (('Yes' if sp['ccs'] else 'No') != a.only_ccs): continue
        cis = [float(x) for x in a.ci.split(",")] if a.ci else (cis_spec or [i * 0.25 for i in range(8)])
        print(f"\n===== site {site_id} · CCS={'Yes' if sp['ccs'] else 'No'} · {len(cis)} CI targets =====")
        run_site(sp, out, a.label, site_id, cis, fallback_lcoa=a.fallback_lcoa)

if __name__ == "__main__":
    main()
